### PR TITLE
Utilize a named profile from .aws/credentials file if profile option …

### LINKED ISSUE #3: Add support for named profile from .aws/credentials file if profile option specified

### PR DESCRIPTION
**Pull request by vandrewskis**
…specified
closes #3

### CODE REVIEW

**Comment by mifi** [comment]
Isn't this accomplished by running dynamodump with AWS_PROFILE=myprofile ?

**Comment by vandrewskis** [comment]
This is a very good question. 👍 

* `--profile` is another way of providing the profile to the dynamodump.
It is modeled per [aws cli](http://docs.aws.amazon.com/cli/latest/userguide/cli-multiple-profiles.html) approach.
* This is convenient way for setting the profile for single command. While AWS_PROFILE=profile can be used for single commands in unix like system, it gets much inconvenient on Windows.
* AWS_PROFILE still works, `--profile` if specified overrides it.

Hope this answers the question. Please let me know if there are any other comments, questions, suggestions?

**Comment by mifi** [comment]
I agree that it can be useful with a `--profile` option, but I think it can be done simpler by doing it a way i think is more "standard" of AWS and more DRY:

```
AWS.config.credentials = new AWS.SharedIniFileCredentials({profile: 'work-account'});
```

http://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/loading-node-credentials-shared.html

**Comment by vandrewskis** [comment]
I hear what you say and it makes sense.

`AWS.SharedIniFileCredentials({profile: 'work-account'});` is in fact used by aws-config in the background.
What this doesn't solve is [profiles with cross account roles](http://docs.aws.amazon.com/cli/latest/userguide/cli-roles.html). aws-config doesn't solve that (yet) either. However, if profiles with cross account roles are to be addressed some day, would you prefer solve it in dynamodump or some other library?

**Comment by mifi** [comment]
Yes I think that if that is a problem later, then we'll have to discuss how to do that.

**Comment by mifi** [comment]
Thanks for your contribution.

**Comment by vandrewskis** [comment]
Thank you for feedback and merge.

On a separate note the cross account roles may be [supported by default with next major version bump in aws sdk js](https://github.com/aws/aws-sdk-js/pull/1391).

**Pull request merged**
