### PR TITLE
use throughput input parameter to do parallel import-data

### PR DESCRIPTION
**Pull request by marcelpanse**
import-data is very slow because it only does 1 putItem at the time. By doing parallel putItems you can speed the import up a lot. You can use the throughput parameter to control the number of parallel uploads. This helped me do an import that would take a day to do in a couple of minutes.

### CODE REVIEW

**Comment by mifi** [comment]
Hi, can you explain how the code works? I see it compares the total inserted rows (n) with throttle, but will that work?

**Comment by marcelpanse** [comment]
@mifi Instead of pausing the stream every single record, it doesn't pause until you reach the throughput number. 
So lets say throughput is 100. Then it won't pause untill it does 100 records simultaneously, then it will pause record 101. When record 1 finishes it will resume the stream and immediately pause it again (so it only processes 1 more record). At the same time record 2 will finish and trigger another resume, etc. 
So in practice you will have 100 puts in parallel during your entire import.

**Comment by mifi** [comment]
But when n reaches 100, then all future data events will pause the stream, right? because n will always stay over 100?

**Comment by mifi** [comment]
Ok, I trust you ;) I think throughput is ok, since we are already using that for wipe data

**Pull request merged**
