### PR TITLE
updated to support ca-file and marshalling/unmarshalling dynamo data

### PR DESCRIPTION
**Pull request by dkhunt27**
updated to support ca-file; 
marshalling/unmarshalling dynamo json to "normal" json;
bumped version to 1.5.0 due to the marshall/unmarshall thing;

### CODE REVIEW

**Comment by mifi** [comment]
Thanks for PR. Isn't Marshalling/unmarshalling a breaking change? Then it should be under a flag.
Also, how does this fix #7 ? There is no way of specifying proxy server

**Comment by dkhunt27** [comment]
I thought the proxy thing was what i was running into, corporate self sign cert issues.  reread it and removed the link to that issue.  also updated the marshalling thing to be an option that you can specify, so no longer a breaking change

**Comment by dkhunt27** [comment]
Anything else needed to get this merged?

**Comment by mifi** [comment]
thnanks

**Pull request merged**
